/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WritingToolsRouteImport } from './routes/writing-tools'
import { Route as UtilitiesRouteImport } from './routes/utilities'
import { Route as SummarizerRouteImport } from './routes/summarizer'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RubricsRouteImport } from './routes/rubrics'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HumanizerRouteImport } from './routes/humanizer'
import { Route as HelpRouteImport } from './routes/help'
import { Route as FormattingRouteImport } from './routes/formatting'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CitationsRouteImport } from './routes/citations'
import { Route as AiDetectorRouteImport } from './routes/ai-detector'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReviewsIndexRouteImport } from './routes/reviews.index'
import { Route as DocumentsIndexRouteImport } from './routes/documents.index'
import { Route as ReviewsWorkspaceRouteImport } from './routes/reviews.workspace'
import { Route as ReviewsIdRouteImport } from './routes/reviews.$id'
import { Route as DocumentsDocumentIdRouteImport } from './routes/documents.$documentId'

const WritingToolsRoute = WritingToolsRouteImport.update({
  id: '/writing-tools',
  path: '/writing-tools',
  getParentRoute: () => rootRouteImport,
} as any)
const UtilitiesRoute = UtilitiesRouteImport.update({
  id: '/utilities',
  path: '/utilities',
  getParentRoute: () => rootRouteImport,
} as any)
const SummarizerRoute = SummarizerRouteImport.update({
  id: '/summarizer',
  path: '/summarizer',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RubricsRoute = RubricsRouteImport.update({
  id: '/rubrics',
  path: '/rubrics',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HumanizerRoute = HumanizerRouteImport.update({
  id: '/humanizer',
  path: '/humanizer',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const FormattingRoute = FormattingRouteImport.update({
  id: '/formatting',
  path: '/formatting',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CitationsRoute = CitationsRouteImport.update({
  id: '/citations',
  path: '/citations',
  getParentRoute: () => rootRouteImport,
} as any)
const AiDetectorRoute = AiDetectorRouteImport.update({
  id: '/ai-detector',
  path: '/ai-detector',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsIndexRoute = ReviewsIndexRouteImport.update({
  id: '/reviews/',
  path: '/reviews/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsIndexRoute = DocumentsIndexRouteImport.update({
  id: '/documents/',
  path: '/documents/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsWorkspaceRoute = ReviewsWorkspaceRouteImport.update({
  id: '/reviews/workspace',
  path: '/reviews/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsIdRoute = ReviewsIdRouteImport.update({
  id: '/reviews/$id',
  path: '/reviews/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsDocumentIdRoute = DocumentsDocumentIdRouteImport.update({
  id: '/documents/$documentId',
  path: '/documents/$documentId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-detector': typeof AiDetectorRoute
  '/citations': typeof CitationsRoute
  '/dashboard': typeof DashboardRoute
  '/formatting': typeof FormattingRoute
  '/help': typeof HelpRoute
  '/humanizer': typeof HumanizerRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/rubrics': typeof RubricsRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/summarizer': typeof SummarizerRoute
  '/utilities': typeof UtilitiesRoute
  '/writing-tools': typeof WritingToolsRoute
  '/documents/$documentId': typeof DocumentsDocumentIdRoute
  '/reviews/$id': typeof ReviewsIdRoute
  '/reviews/workspace': typeof ReviewsWorkspaceRoute
  '/documents/': typeof DocumentsIndexRoute
  '/reviews/': typeof ReviewsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-detector': typeof AiDetectorRoute
  '/citations': typeof CitationsRoute
  '/dashboard': typeof DashboardRoute
  '/formatting': typeof FormattingRoute
  '/help': typeof HelpRoute
  '/humanizer': typeof HumanizerRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/rubrics': typeof RubricsRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/summarizer': typeof SummarizerRoute
  '/utilities': typeof UtilitiesRoute
  '/writing-tools': typeof WritingToolsRoute
  '/documents/$documentId': typeof DocumentsDocumentIdRoute
  '/reviews/$id': typeof ReviewsIdRoute
  '/reviews/workspace': typeof ReviewsWorkspaceRoute
  '/documents': typeof DocumentsIndexRoute
  '/reviews': typeof ReviewsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-detector': typeof AiDetectorRoute
  '/citations': typeof CitationsRoute
  '/dashboard': typeof DashboardRoute
  '/formatting': typeof FormattingRoute
  '/help': typeof HelpRoute
  '/humanizer': typeof HumanizerRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/rubrics': typeof RubricsRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/summarizer': typeof SummarizerRoute
  '/utilities': typeof UtilitiesRoute
  '/writing-tools': typeof WritingToolsRoute
  '/documents/$documentId': typeof DocumentsDocumentIdRoute
  '/reviews/$id': typeof ReviewsIdRoute
  '/reviews/workspace': typeof ReviewsWorkspaceRoute
  '/documents/': typeof DocumentsIndexRoute
  '/reviews/': typeof ReviewsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-detector'
    | '/citations'
    | '/dashboard'
    | '/formatting'
    | '/help'
    | '/humanizer'
    | '/login'
    | '/profile'
    | '/rubrics'
    | '/settings'
    | '/signup'
    | '/summarizer'
    | '/utilities'
    | '/writing-tools'
    | '/documents/$documentId'
    | '/reviews/$id'
    | '/reviews/workspace'
    | '/documents/'
    | '/reviews/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-detector'
    | '/citations'
    | '/dashboard'
    | '/formatting'
    | '/help'
    | '/humanizer'
    | '/login'
    | '/profile'
    | '/rubrics'
    | '/settings'
    | '/signup'
    | '/summarizer'
    | '/utilities'
    | '/writing-tools'
    | '/documents/$documentId'
    | '/reviews/$id'
    | '/reviews/workspace'
    | '/documents'
    | '/reviews'
  id:
    | '__root__'
    | '/'
    | '/ai-detector'
    | '/citations'
    | '/dashboard'
    | '/formatting'
    | '/help'
    | '/humanizer'
    | '/login'
    | '/profile'
    | '/rubrics'
    | '/settings'
    | '/signup'
    | '/summarizer'
    | '/utilities'
    | '/writing-tools'
    | '/documents/$documentId'
    | '/reviews/$id'
    | '/reviews/workspace'
    | '/documents/'
    | '/reviews/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiDetectorRoute: typeof AiDetectorRoute
  CitationsRoute: typeof CitationsRoute
  DashboardRoute: typeof DashboardRoute
  FormattingRoute: typeof FormattingRoute
  HelpRoute: typeof HelpRoute
  HumanizerRoute: typeof HumanizerRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  RubricsRoute: typeof RubricsRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  SummarizerRoute: typeof SummarizerRoute
  UtilitiesRoute: typeof UtilitiesRoute
  WritingToolsRoute: typeof WritingToolsRoute
  DocumentsDocumentIdRoute: typeof DocumentsDocumentIdRoute
  ReviewsIdRoute: typeof ReviewsIdRoute
  ReviewsWorkspaceRoute: typeof ReviewsWorkspaceRoute
  DocumentsIndexRoute: typeof DocumentsIndexRoute
  ReviewsIndexRoute: typeof ReviewsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/writing-tools': {
      id: '/writing-tools'
      path: '/writing-tools'
      fullPath: '/writing-tools'
      preLoaderRoute: typeof WritingToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/utilities': {
      id: '/utilities'
      path: '/utilities'
      fullPath: '/utilities'
      preLoaderRoute: typeof UtilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/summarizer': {
      id: '/summarizer'
      path: '/summarizer'
      fullPath: '/summarizer'
      preLoaderRoute: typeof SummarizerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rubrics': {
      id: '/rubrics'
      path: '/rubrics'
      fullPath: '/rubrics'
      preLoaderRoute: typeof RubricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/humanizer': {
      id: '/humanizer'
      path: '/humanizer'
      fullPath: '/humanizer'
      preLoaderRoute: typeof HumanizerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formatting': {
      id: '/formatting'
      path: '/formatting'
      fullPath: '/formatting'
      preLoaderRoute: typeof FormattingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citations': {
      id: '/citations'
      path: '/citations'
      fullPath: '/citations'
      preLoaderRoute: typeof CitationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-detector': {
      id: '/ai-detector'
      path: '/ai-detector'
      fullPath: '/ai-detector'
      preLoaderRoute: typeof AiDetectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews/': {
      id: '/reviews/'
      path: '/reviews'
      fullPath: '/reviews/'
      preLoaderRoute: typeof ReviewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/': {
      id: '/documents/'
      path: '/documents'
      fullPath: '/documents/'
      preLoaderRoute: typeof DocumentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews/workspace': {
      id: '/reviews/workspace'
      path: '/reviews/workspace'
      fullPath: '/reviews/workspace'
      preLoaderRoute: typeof ReviewsWorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews/$id': {
      id: '/reviews/$id'
      path: '/reviews/$id'
      fullPath: '/reviews/$id'
      preLoaderRoute: typeof ReviewsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/$documentId': {
      id: '/documents/$documentId'
      path: '/documents/$documentId'
      fullPath: '/documents/$documentId'
      preLoaderRoute: typeof DocumentsDocumentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiDetectorRoute: AiDetectorRoute,
  CitationsRoute: CitationsRoute,
  DashboardRoute: DashboardRoute,
  FormattingRoute: FormattingRoute,
  HelpRoute: HelpRoute,
  HumanizerRoute: HumanizerRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  RubricsRoute: RubricsRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  SummarizerRoute: SummarizerRoute,
  UtilitiesRoute: UtilitiesRoute,
  WritingToolsRoute: WritingToolsRoute,
  DocumentsDocumentIdRoute: DocumentsDocumentIdRoute,
  ReviewsIdRoute: ReviewsIdRoute,
  ReviewsWorkspaceRoute: ReviewsWorkspaceRoute,
  DocumentsIndexRoute: DocumentsIndexRoute,
  ReviewsIndexRoute: ReviewsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
